/* Historical and traditional oil pigments for the Oil Studio color picker.
   Hex values are approximate masstone colors of the paint straight from the tube. */
export const FAMILIES = ["Whites", "Yellows", "Oranges", "Reds", "Pinks & Violets", "Blues", "Greens", "Earths", "Grays & Blacks"];
export const PIGMENTS = [
  ["Whites", "Titanium White", "#f4f1ea"],
  ["Whites", "Lead White", "#efe9da"],
  ["Whites", "Zinc White", "#f2f3ef"],
  ["Whites", "Cremnitz White", "#ede5d2"],
  ["Whites", "Unbleached Titanium", "#e2d6bf"],
  ["Yellows", "Lemon Yellow", "#f2e33a"],
  ["Yellows", "Cadmium Yellow", "#f2c200"],
  ["Yellows", "Naples Yellow", "#f0cf7c"],
  ["Yellows", "Indian Yellow", "#e9a512"],
  ["Yellows", "Chrome Yellow", "#f5b800"],
  ["Yellows", "Aureolin", "#f2d33c"],
  ["Yellows", "Lead-Tin Yellow", "#ecd67a"],
  ["Yellows", "Gamboge", "#e4a11c"],
  ["Yellows", "Hansa Yellow", "#f7d117"],
  ["Oranges", "Cadmium Orange", "#ec7a16"],
  ["Oranges", "Realgar", "#e5672a"],
  ["Oranges", "Orpiment", "#e9b33a"],
  ["Oranges", "Mars Orange", "#c4612a"],
  ["Reds", "Cadmium Red", "#d83a2e"],
  ["Reds", "Vermilion", "#e34234"],
  ["Reds", "Alizarin Crimson", "#8e1c3a"],
  ["Reds", "Rose Madder", "#d4527a"],
  ["Reds", "Carmine", "#a3102a"],
  ["Reds", "Red Lead", "#d3492b"],
  ["Reds", "Scarlet Lake", "#e0303b"],
  ["Reds", "Indian Red", "#8c3b2e"],
  ["Reds", "Venetian Red", "#a2402c"],
  ["Reds", "Quinacridone Red", "#c4214b"],
  ["Pinks & Violets", "Quinacridone Magenta", "#a3245e"],
  ["Pinks & Violets", "Cobalt Violet", "#8b4f9e"],
  ["Pinks & Violets", "Manganese Violet", "#6f3f8c"],
  ["Pinks & Violets", "Dioxazine Purple", "#4b2a6e"],
  ["Pinks & Violets", "Tyrian Purple", "#66023c"],
  ["Pinks & Violets", "Mauve", "#915f9d"],
  ["Blues", "Ultramarine Blue", "#1e3a8a"],
  ["Blues", "Cobalt Blue", "#3e76ba"],
  ["Blues", "Prussian Blue", "#1b3550"],
  ["Blues", "Phthalo Blue", "#0f2f73"],
  ["Blues", "Cerulean Blue", "#2a7ab0"],
  ["Blues", "Manganese Blue", "#2d8ba8"],
  ["Blues", "Indigo", "#2a2f55"],
  ["Blues", "Azurite", "#2c5c9c"],
  ["Blues", "Smalt", "#4a5f9e"],
  ["Blues", "Egyptian Blue", "#1f63a6"],
  ["Blues", "Payne's Gray", "#3d4a5a"],
  ["Greens", "Viridian", "#1f6a45"],
  ["Greens", "Phthalo Green", "#0f5c45"],
  ["Greens", "Sap Green", "#3e6b28"],
  ["Greens", "Terre Verte", "#6f7e5a"],
  ["Greens", "Chromium Oxide Green", "#5a7a3e"],
  ["Greens", "Emerald Green", "#2fa36b"],
  ["Greens", "Verdigris", "#3f8a7a"],
  ["Greens", "Hooker's Green", "#2f5e3a"],
  ["Greens", "Olive Green", "#6b6b2a"],
  ["Greens", "Cobalt Green", "#4ba889"],
  ["Earths", "Yellow Ochre", "#c69230"],
  ["Earths", "Raw Sienna", "#b9803a"],
  ["Earths", "Burnt Sienna", "#8a3c1e"],
  ["Earths", "Raw Umber", "#6b5434"],
  ["Earths", "Burnt Umber", "#6a3b22"],
  ["Earths", "Van Dyke Brown", "#4a3426"],
  ["Earths", "Mars Yellow", "#c78a2c"],
  ["Earths", "Gold Ochre", "#c2862a"],
  ["Earths", "Caput Mortuum", "#5b2f33"],
  ["Earths", "Bitumen", "#3a2a1c"],
  ["Earths", "Mummy Brown", "#5a3b26"],
  ["Grays & Blacks", "Ivory Black", "#302c28"],
  ["Grays & Blacks", "Lamp Black", "#2a2a2c"],
  ["Grays & Blacks", "Mars Black", "#262524"],
  ["Grays & Blacks", "Vine Black", "#34332f"],
  ["Grays & Blacks", "Davy's Gray", "#8a8578"],
  ["Grays & Blacks", "Neutral Tint", "#4b4a50"]
].map(([family, name, hex]) => ({ family, name, hex, rgb: [1, 3, 5].map(i => parseInt(hex.slice(i, i + 2), 16)) }));
