/* Historical and traditional oil pigments for the Oil Studio color picker.
   Hex values are approximate masstone colors of the paint straight from the tube. */
export const FAMILIES = ["Whites", "Yellows", "Oranges", "Reds", "Pinks & Violets", "Blues", "Greens", "Earths", "Grays & Blacks"];
export const PIGMENTS = [
  ["Whites", "Titanium White", "#f4f1ea", "Bright, opaque white, made for artists from the 1920s."],
  ["Whites", "Lead White", "#efe9da", "Also called Flake White. The painters' white from antiquity to the 1900s."],
  ["Whites", "Zinc White", "#f2f3ef", "Cool, transparent white sold as Chinese White from 1834."],
  ["Whites", "Cremnitz White", "#ede5d2", "A fine lead white named for Kremnica, now in Slovakia."],
  ["Whites", "Unbleached Titanium", "#e2d6bf", "Warm off-white titanium, loved for skin tones and sand."],
  ["Yellows", "Lemon Yellow", "#f2e33a", "Cool, greenish yellow, first made from barium chromate in the 1800s."],
  ["Yellows", "Cadmium Yellow", "#f2c200", "Bright, opaque yellow, made from 1840s cadmium sulfide. Monet loved it."],
  ["Yellows", "Naples Yellow", "#f0cf7c", "Lead antimonate, used since ancient Babylon and named for Vesuvius."],
  ["Yellows", "Indian Yellow", "#e9a512", "Glowing glaze once made in Bengal and shipped to Europe in balls."],
  ["Yellows", "Chrome Yellow", "#f5b800", "A Van Gogh sunflower yellow, first made in 1809."],
  ["Yellows", "Aureolin", "#f2d33c", "Cobalt yellow from 1851, clear and transparent."],
  ["Yellows", "Lead-Tin Yellow", "#ecd67a", "The yellow of Vermeer and the Renaissance, lost and rediscovered in 1941."],
  ["Yellows", "Gamboge", "#e4a11c", "Tree resin from Cambodia, used in Asian art for centuries."],
  ["Yellows", "Hansa Yellow", "#f7d117", "Modern azo yellow, invented in Germany in 1909."],
  ["Oranges", "Cadmium Orange", "#ec7a16", "Warm, opaque orange from the cadmium family, around 1900."],
  ["Oranges", "Realgar", "#e5672a", "Arsenic mineral orange used in old Egypt and Venice."],
  ["Oranges", "Orpiment", "#e9b33a", "Golden arsenic yellow, the 'king's yellow' of ancient scribes."],
  ["Oranges", "Mars Orange", "#c4612a", "Man-made iron oxide orange from the 1800s."],
  ["Reds", "Cadmium Red", "#d83a2e", "Rich, opaque red sold from 1910 as a safer swap for vermilion."],
  ["Reds", "Vermilion", "#e34234", "Mercury sulfide red, prized from Roman times to the Renaissance."],
  ["Reds", "Alizarin Crimson", "#8e1c3a", "Synthetic madder lake from 1868, deep and transparent."],
  ["Reds", "Rose Madder", "#d4527a", "Madder root lake, used since ancient Egypt for soft rose glazes."],
  ["Reds", "Carmine", "#a3102a", "Lake made from cochineal insects, brought to Europe from Mexico in the 1500s."],
  ["Reds", "Red Lead", "#d3492b", "Minium, the medieval red behind the word 'miniature'."],
  ["Reds", "Scarlet Lake", "#e0303b", "Bright transparent red of the Victorian palette."],
  ["Reds", "Indian Red", "#8c3b2e", "Cool iron oxide red, first shipped from India."],
  ["Reds", "Venetian Red", "#a2402c", "Warm iron red of the Venetian masters."],
  ["Reds", "Quinacridone Red", "#c4214b", "Modern lightfast red from 1958."],
  ["Pinks & Violets", "Quinacridone Magenta", "#a3245e", "Modern clear magenta, a cool pink for glazing."],
  ["Pinks & Violets", "Cobalt Violet", "#8b4f9e", "Rare cobalt violet from 1859, soft and pricey."],
  ["Pinks & Violets", "Manganese Violet", "#6f3f8c", "Mineral violet from 1868, also called Nuremberg Violet."],
  ["Pinks & Violets", "Dioxazine Purple", "#4b2a6e", "Powerful modern purple from 1928."],
  ["Pinks & Violets", "Tyrian Purple", "#66023c", "Imperial purple from sea snails, worn by Roman emperors."],
  ["Pinks & Violets", "Mauve", "#915f9d", "Perkin's 1856 mauveine, the first synthetic dye."],
  ["Blues", "Ultramarine Blue", "#1e3a8a", "Once ground from lapis lazuli and worth more than gold. Synthetic since 1828."],
  ["Blues", "Cobalt Blue", "#3e76ba", "Clean, steady blue made by Thénard in 1802."],
  ["Blues", "Prussian Blue", "#1b3550", "Accidentally discovered in Berlin in 1704. Hokusai's Great Wave blue."],
  ["Blues", "Phthalo Blue", "#0f2f73", "Super strong modern blue from 1935. A little goes a long way."],
  ["Blues", "Cerulean Blue", "#2a7ab0", "Sky blue from 1860, made famous by plein-air painters."],
  ["Blues", "Manganese Blue", "#2d8ba8", "Clear turquoise blue from 1935, now made as a hue."],
  ["Blues", "Indigo", "#2a2f55", "Plant dye from India, traded along the Silk Road."],
  ["Blues", "Azurite", "#2c5c9c", "Copper mineral blue of medieval and Renaissance skies."],
  ["Blues", "Smalt", "#4a5f9e", "Ground cobalt glass, used in the 1500s and 1600s."],
  ["Blues", "Egyptian Blue", "#1f63a6", "The first man-made pigment, from about 2500 BC."],
  ["Blues", "Payne's Gray", "#3d4a5a", "Blue-gray mix named for William Payne, around 1800."],
  ["Greens", "Viridian", "#1f6a45", "Cool, transparent chromium green from 1838."],
  ["Greens", "Phthalo Green", "#0f5c45", "Intense modern green from 1938."],
  ["Greens", "Sap Green", "#3e6b28", "Once buckthorn berry juice. A warm landscape green."],
  ["Greens", "Terre Verte", "#6f7e5a", "Green earth, the underpainting for skin in medieval art."],
  ["Greens", "Chromium Oxide Green", "#5a7a3e", "Opaque, earthy green from 1862."],
  ["Greens", "Emerald Green", "#2fa36b", "Arsenic Paris green from 1814, loved by Cézanne. Today a safe hue."],
  ["Greens", "Verdigris", "#3f8a7a", "Copper rust green used in medieval and Renaissance paintings."],
  ["Greens", "Hooker's Green", "#2f5e3a", "Leafy green named for botanical artist William Hooker."],
  ["Greens", "Olive Green", "#6b6b2a", "Old-fashioned mixed green for foliage."],
  ["Greens", "Cobalt Green", "#4ba889", "Rinmann's green from 1780, cool and gentle."],
  ["Earths", "Yellow Ochre", "#c69230", "Natural clay yellow used in cave paintings 40,000 years ago."],
  ["Earths", "Raw Sienna", "#b9803a", "Earth from Siena, Italy. Warm and golden."],
  ["Earths", "Burnt Sienna", "#8a3c1e", "Roasted Siena earth, a rich red-brown."],
  ["Earths", "Raw Umber", "#6b5434", "Cool brown earth from Umbria, Italy. Great for drawing in."],
  ["Earths", "Burnt Umber", "#6a3b22", "Roasted umber, the warm brown of Rembrandt's shadows."],
  ["Earths", "Van Dyke Brown", "#4a3426", "Peat-based brown named for the painter Anthony van Dyck."],
  ["Earths", "Mars Yellow", "#c78a2c", "Man-made iron oxide yellow from the 1800s."],
  ["Earths", "Gold Ochre", "#c2862a", "Deep golden earth for warm light."],
  ["Earths", "Caput Mortuum", "#5b2f33", "Purple iron oxide whose Latin name means 'dead head'."],
  ["Earths", "Bitumen", "#3a2a1c", "Tar brown of the 1700s and 1800s. It never dried, so it cracked."],
  ["Earths", "Mummy Brown", "#5a3b26", "Truly made from ground mummies until the 1900s."],
  ["Grays & Blacks", "Ivory Black", "#302c28", "Once burnt ivory, now bone. Velázquez's warm black."],
  ["Grays & Blacks", "Lamp Black", "#2a2a2c", "Soot from oil lamps, one of the oldest blacks."],
  ["Grays & Blacks", "Mars Black", "#262524", "Dense, opaque iron oxide black from the 1900s."],
  ["Grays & Blacks", "Vine Black", "#34332f", "Charred grapevines, a soft bluish black."],
  ["Grays & Blacks", "Davy's Gray", "#8a8578", "Ground slate gray from the 1890s, named for Henry Davy."],
  ["Grays & Blacks", "Neutral Tint", "#4b4a50", "Cool gray-black for glazing shadows."]
].map(([family, name, hex, note]) => ({ family, name, hex, note, rgb: [1, 3, 5].map(i => parseInt(hex.slice(i, i + 2), 16)) }));
